### PR TITLE
feat: persist app window size and position

### PR DESCRIPTION
**Pull request by MiaoMint**

### CODE REVIEW

**Review by appdevelpo — APPROVED** [review]

**Comment by bachig26** [comment]
@MiaoMint it still has some issues with this.
sometimes it works like remembers the position but not the size, sometimes it doesn't remember both size and position like this clip.

https://github.com/miru-project/miru-app/assets/96393348/a76f8648-bea6-4888-a67f-ebbae4e8296e

**Comment by bachig26** [comment]
it still needs some fix.

**Comment by MiaoMint** [comment]
> it still needs some fix.

This is normal, maximization will not be remembered

**Comment by bachig26** [comment]
@MiaoMint can you also able to add this feature to the `Extension Log Window` and the AniList `Login Window`?

**Pull request merged**
