### PR TITLE
feat: New reader for Comic and Novel

### LINKED ISSUE #175: [Android] Hide navigation bar
### Describe your suggested feature

When reading a comic or novel, hide the navigation bar.

Due to personal experience with other apps, I believe currently with high brightness and long use, the navigation bar could cause screen burn-in as it never hides.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

### PR DESCRIPTION
**Pull request by appdevelpo**
fix:full screen in comic and novel reader,
feat(indicator bar): battery indicator,
feat:wakelock
feat:fullscreen in novel and comic

### CODE REVIEW

**Comment by OshekharO** [comment]
From indicator alignment text such as bottom left , bottom right and so on can be removed just an icon is good. Also i18 values have not been added?

Screenshot_20240127-132521_Miru

Instead of tgta big texts just Autoscroll is good . ( this minor thing need to be done with every text ).

**Comment by appdevelpo** [comment]
image

**Comment by OshekharO** [comment]
reader

How about this ui and features

**Comment by appdevelpo** [comment]
Plan to work on tts

**Comment by bachig26** [comment]
@appdevelpo does this new reader compatible with the new player? I haven’t tried this pr yet and looks like the new video player pr isn’t included here.

**Comment by appdevelpo** [comment]
I have  issues commiting on this branch. I'll  restart a new branch and new pr if I can't handle it.

**Pull request closed without merging**
