### PR TITLE
feat/new comic and novel reader

### PR DESCRIPTION
**Pull request by appdevelpo**

### CODE REVIEW

**Comment by OshekharO** [comment]
None of the novel extension working after updating to this dev version. And how about the setting ui for comics and novel I mentioned in earlier draft? And also infinityscroll for novels.

**Comment by appdevelpo** [comment]
To do : 
~~for finished~~
~~Infinity scroll for novel~~
i18n 
~~tts~~
indicator alignment icon in setting (comic)
indicator for novel
more setting in novel
enhance infinity scroll 
single page flipping book mode for novel

**Comment by OshekharO** [comment]
None of the novel extension working after updating to this dev version. What about this?

**Comment by appdevelpo** [comment]
new novel command bar
image

**Comment by OshekharO** [comment]
Is there any way to add inbuilt translator in novel reader? And i18 is probably incomplete in regards to novel and manga settings.

**Comment by OshekharO** [comment]
Screenshot_20240219-075239_Miru
Screenshot_20240219-075249_Miru

i18 not set for some texts

**Comment by OshekharO** [comment]
Also infinity scroll doesn't keep track of chapter number, this will be a problem.

**Comment by OshekharO** [comment]
Novel thing fixed??

**Comment by OshekharO** [comment]
Novel content thing fixed?

**Pull request closed without merging**
