### PR TITLE
feat: new video player

### LINKED ISSUE #89: support DLNA cast to tv 支持投屏功能
### Describe your suggested feature

This is very useful for video playback on TV.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

### LINKED ISSUE #108: [Windows] add `MinimizeToTaskBar` button in player
### Describe your suggested feature

I'd like to see a button for minimizing the app to taskbar in the video player mode, this can be useful in lot of case.

**I know that I can use `WinKey + DownArrow` to minimize the app, but while in fullscreen this doesn't work as I need to use these keys twice to get it done.**

### Screenshot
VLs3qEYRqn

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

### LINKED ISSUE #121: [Windows] PiP support (if not possible, few other suggestions)
### Describe your suggested feature

I'm suggesting the PiP support to have the video player to play as `Always onTop`.

if this possible, I would like to the PiP feature or the Always onTop feature in the app.
if not possible, 
I would to see other alternative feature like,
1. having an different player like `HTML5 Video Player` with an option in the settings to change between the default and the HTML5 Player. I'm suggesting this as I've seen in it in [iptvnator](https://github.com/4gray/iptvnator), even though it's not flutter but the option for player is nice which gives an advantage one over other.
2. in other case of having the [Vidstack](https://www.vidstack.io/) which is still in as pre-release.

i'm not sure if this will be feasible to bring to life for miru, but i'd like to have this feature suggestion made here.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

### LINKED ISSUE #154: 建议默认播放器增加长按倍速功能
### Describe your suggested feature

使用第三方播放器，会导致首页番剧图片无法显示，建议优化内置播放器

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

### LINKED ISSUE #178: [Windows] App - Always onTop
### Describe your suggested feature

i have few suggestions for this feature (which is similar to the other apps like a video player or notepad++ where it can be left always on top other running apps).

1. add an option to toggle to set the miru app being `onTop`.

2. since onTop feature important for the video player, which the current built-in player lacks, i'm not sure on the [new branch for player](https://github.com/miru-project/miru-app/tree/feat/better-video-player). but if there's an PiP support #121 comes then it's an plus.
@MiaoMint fyi, issue #121 is for the suggestion no.2, not no.1; just want to remind you in the current state on the new branch for the video player.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

### LINKED ISSUE #206: Remember selected subtitle language
### Describe your suggested feature

Currently when you start playback of an episode and select the subtitle, it only remembers the subtitle language while it remains focused. e.g: going back to the series menu will reset the subtitle language to none. Same goes for going to the next episode. 

How to reproduce:
1. Start playing a show
2. Change the subtitles language to anything except none
3. Change episodes or otherwise stop watching the current episode
4. Go back to that episode
You will now see that the subtitles have been defaulted back to none.

I understand that defaulting to no subtitles is a very safe default since subtitles are not always available but I am of the opinion that this is a valuable QoL feature.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

### PR DESCRIPTION
**Pull request by MiaoMint**
image

### CODE REVIEW

**Comment by bachig26** [comment]
@MiaoMint as you can see in the screenshot, the settings button is covered when the app isn't in a fullscreen or at a certain window size and we can't access the button (for now say, this settings button), and the user need to re-size the window to use it.

this issue was also present in the public version (1.8.1 or earlier) of miru when you use the "Play List" button, please make it not have a conflict with the buttons due the vertical tabs/lists.

miru_NjmHyCRkFt

**Comment by bachig26** [comment]
@MiaoMint 
few other suggestions:

1. also, it sounds better having `streamlink` instead of `play link`?

miru_YS1tPmOzvE

2. better seekbar, the previous was nice since it shows the cached/buffered length of the video. and also as you can see the duration isn't good, example instead of `1:09 (minutes)` it shows as `1:9` and it's completely in minutes now instead of as hours (whihc i don't mind). but it's not perfect.

miru_PcYWevXVy6

3. also the volume option doesn't support the mouse middle button scroll over to change the volume. previously it was possible.

**Comment by MiaoMint** [comment]
image
image

**Comment by bachig26** [comment]
@MiaoMint can you also add the "Rewind", "Fast-Forward" button for skipping along the play button?
if possible similar to this?

vivaldi_oMDW80XiLS
vivaldi_QDM807bO8k
vivaldi_vbdfZkGNAq

**Comment by OffLine911** [comment]
Thanks you it becomes perfect, now we will need multiple sources for the video, but what about android app? Can I test it.

**Comment by bachig26** [comment]
the new video player has some bug with the play button as you can see in the clip, it shows as 'play' instead of 'pause' icon. i had to press twice to make the video pause as shown.

https://github.com/miru-project/miru-app/assets/96393348/63f81645-024e-4c78-856d-58619cae9015

**Comment by bachig26** [comment]
a must needed improvement/feature to the video player:

- **Jump to next season**: with this new and old player, we can jump to the next season while in the player, as the user need to change it in detail page and access episode. as you know at present, the user can only access the episodes on the current season they're on inside the player play list.

@MiaoMint please have a look at this and possibility in having it for the new video player.
it's wasn't comfortable with the old player and also not with the new player, while binge watching it's always an hassle and annoying to go back to the detail page.

**Comment by bachig26** [comment]
also i'm still seeing the play pause button mismatch issue as i have mentioned in a above comment happened again while i'm was accessing the audio track option.

**Comment by bachig26** [comment]
@MiaoMint is it possible make an custom option to define the position of the buttons (settings, volume, play list, etc) in video player. so, the user can move it like top right, bottom left, etc.?

**Comment by MiaoMint** [comment]
> @MiaoMint is it possible make an custom option to define the position of the buttons (settings, volume, play list, etc) in video player. so, the user can move it like top right, bottom left, etc.?

No plans yet

**Comment by bachig26** [comment]
thanks for the remember subtitle function, it's nice.

and also just noticed that there's no mute function, i tried to click the volume button (outside and within the volume slider) but it seems not available. can you able add it?

**Pull request merged**
