### PR TITLE
add functions for extension

### PR DESCRIPTION
**Pull request by appdevelpo**
add updatePages and RequestWithHeader
updatePages: after calling watch and return with pages param , you can access pages from js side with updatePages(page).
Testing code for Ehentai: https://github.com/appdevelpo/repo/blob/main/repo/ehentai.org.js
RequestWithHeader: js side will receive response header that this.request lacks of

### CODE REVIEW

**Comment by appdevelpo** [comment]
Concerning why android did not support skipping is because the skipping time has been coded as a const. See : https://github.com/media-kit/media-kit/blob/0ab6b10ea660ead8e8e1694517aabe3582f25d5c/media_kit_video/lib/media_kit_video_controls/src/controls/material.dart#L1926

**Comment by bachig26** [comment]
@appdevelpo 
1. can you add the skipInterval format in `s` instead of `ms`, possibly a conversion system so the user doesn't have to input in ms.
2. if possible/useful in long-term, add a dial system for inputting the skipInterval.

**Comment by appdevelpo** [comment]
showcase for setting menu
image

**Comment by appdevelpo** [comment]
@MiaoMint   I've update workflow which success on my repo 
image

**Comment by bachig26** [comment]
@appdevelpo @MiaoMint 
https://github.com/miru-project/miru-app/actions/runs/7069769722

[build-and-release-windows](https://github.com/miru-project/miru-app/actions/runs/7069769722/job/19246271755#step:7:10)
No files were found with the provided path: build/windows/runner/Miru-App. No artifacts will be uploaded.

**Comment by appdevelpo** [comment]
> > image  showcase for both android and desktop version
> 
> How does it detect that whether there is an other steaming quality url available or not?
the hls file look like this:
`#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=720264,RESOLUTION=720x368,CODECS="avc1.4d401f,mp4a.40.2"
https://s39.openstream.io/hls/qvsbizuamxblgwsztsykazohkstlm6j2jymmlgmmjxzab6t25epvkoux3yca/index-v1-a1.m3u8`
this is an example playlist contain one resolution 
It will grab `RESOLUTION` and  links automatically

**Comment by bachig26** [comment]
@appdevelpo the settings backup/restore works well.
i would like to suggest couple of improvements to them if possible.
1. show timestamp of the backup when importing them on the toast or along the Backup text.
2. also export the information of the installed extensions, possibly this helps to avoid the extra work of installing them manually.

**Comment by appdevelpo** [comment]
The backup file name has already coded date time on it maybe it meet your timestamp requirement. Concerning adding the `/backup` folder part , I don't think it's necessary now unless I add something like snapshot function.

**Comment by bachig26** [comment]
@appdevelpo if you can add it, 
can also add couple of following feature relating to the color?
1. new theme `midnight` (example: similar to the discord apps midnight theme).
miru_s3wxkqK48h

2. add accent color feature to select user-selectable instead of the default `blue`.
miru_eyZKVglQBI

**Comment by OshekharO** [comment]
Also you can try #114 #115 #107 #97 #98 #93 #12 #121

**Comment by MiaoMint** [comment]
I think the backup should not be a direct backup of the database files, but should be serialised into a specially encoded text file (e.g. a json file) to make it easier for the web platform to restore the backups.

**Pull request merged**
